Repository FreeHunt/freehunt, pull requests merged in 2025-07, with the labels that each got.

#112 Feat/script seed prod
  backend/package-lock.json
  backend/package.json
  backend/prisma/seed-prod.ts
Labels: enhancement

#136 Use strings for CPU reservation values
  compose.prod.yaml
Labels: deployment

#137 Remove placement constraints for authentik and matomo services in pro…
  compose.prod.yaml
Labels: deployment

#139 Use Traefik in production compose file
  compose.prod.yaml
  traefik/traefik.yml
Labels: deployment

#140 Use Traefik in production compose file
  compose.prod.yaml
Labels: deployment

#142 Fix Traefik swarm mode
  compose.prod.yaml
  traefik/traefik.yml
Labels: deployment

#143 Fix Traefik service ports for Matomo and Uptime Kuma
  compose.prod.yaml
Labels: deployment

#144 Remove resource reservations for non-critical services
  compose.prod.yaml
Labels: deployment

#146 Enhance WebSocket connections with credentials support
  backend/src/common/chat/chat.service.ts
  frontend/actions/conversations.ts
  frontend/components/common/conversation/conversation.tsx
  frontend/hooks/useSocket.ts
Labels: backend, frontend

#147 Remove 'order: start-first' from all services
  compose.prod.yaml
Labels: deployment

#155 Refactor resource limits and reservations in Docker Swarm cluster for…
  compose.prod.yaml
Labels: deployment
