Repository FreeHunt/freehunt, pull requests merged in 2025-05, with the labels that each got.

#44 Fh 50/company register
  frontend/actions/register.ts
  frontend/app/register/company/page.tsx
  frontend/components/common/card/CompanyPreviewCard.tsx
  frontend/components/register/FormContainer.tsx
  frontend/components/register/FormNavigator.tsx
  frontend/components/register/RegisterPageLayout.tsx
  frontend/components/register/form/company/CompanyAddressSection.tsx
  frontend/components/register/form/company/CompanyDescriptionSection.tsx
  frontend/components/register/form/company/CompanyIdentitySection.tsx
  frontend/components/register/form/company/CompanyLogoSection.tsx
  frontend/components/ui/textarea.tsx
  frontend/hooks/useCompanyFormData.ts
  frontend/hooks/useMultiStepForm.ts
Labels: frontend

#47 Fh 54/dockerize frontend
  .github/workflows/node.js.yml
  frontend/Dockerfile
  frontend/app/freelances/search/page.tsx
  frontend/app/job-postings/search/page.tsx
  frontend/app/register/page.tsx
  frontend/components/job-posting/card/index.tsx
  frontend/components/register/form/company/CompanyAddressSection.tsx
  frontend/components/register/form/company/CompanyDescriptionSection.tsx
  frontend/components/register/form/company/CompanyIdentitySection.tsx
  frontend/components/register/form/company/CompanyLogoSection.tsx
  frontend/next.config.ts
Labels: frontend, deployment, config

#48 Enhance CI/CD pipeline with vulnerability scanning and continuous deployment of frontend
  .github/workflows/node.js.yml
Labels: deployment, config

#46 Back register Freelance + Minio upload
  backend/package-lock.json
  backend/package.json
  backend/prisma/fake-data.ts
  backend/prisma/migrations/20250503180732_avatar/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.service.ts
  backend/src/common/authentik/authentik.service.ts
  backend/src/common/authentik/dto/user-info.dto.ts
  backend/src/common/upload/upload.controller.ts
  backend/src/common/upload/upload.module.ts
  backend/src/common/upload/upload.service.ts
  backend/src/main.ts
  backend/src/users/users.controller.ts
  compose.yaml
  frontend/actions/auth.ts
  frontend/actions/register.ts
  frontend/app/register/choice/page.tsx
  frontend/app/register/freelance/page.tsx
  frontend/components/common/banner/TipBox.tsx
  frontend/components/common/card/PreviewCard.tsx
  frontend/components/common/upload/ProfilUploader.tsx
  frontend/components/navigation-menu.tsx
  frontend/components/register/form/AvatarSection.tsx
  frontend/components/register/form/IdentitySection.tsx
  frontend/components/register/form/LocationSection.tsx
  frontend/components/register/form/SkillSection.tsx
  frontend/lib/api.ts
  frontend/package-lock.json
  frontend/package.json
Labels: backend, frontend

#50 [FH-53] Dockerize backend
  .dockerignore
  backend/Dockerfile
  backend/start.sh
Labels: backend, deployment, config

#49 Fh 49/login page
  frontend/app/login/page.tsx
Labels: frontend

#51 Fh 56/ Matomo
  .env
  compose.yaml
  frontend/app/layout.tsx
  frontend/components/MatomoScript.tsx
Labels: deployment

#55 Fh 71/docker swarm manual deployment
  .github/workflows/node.js.yml
  compose.prod.yaml
  compose.yaml
Labels: deployment

#57 Fix ci frontend deployment
  .github/workflows/node.js.yml
  frontend/app/layout.tsx
Labels: deployment, config

#58 Fix ci frontend deployment
  .github/workflows/node.js.yml
Labels: deployment, config

#59 Allow CI/CD workflow to be triggered manually
  .github/workflows/node.js.yml
Labels: deployment, config

#60 Fix ci frontend deployment
  .github/workflows/node.js.yml
  compose.yaml
Labels: deployment, config

#61 Fix Docker configuration for production with Swarm
  compose.prod.yaml
  frontend/Dockerfile
Labels: deployment, config

#62 Fix docker prod config
  frontend/Dockerfile
Labels: deployment, config

#63 Fix docker prod config
  .github/workflows/node.js.yml
  compose.prod.yaml
  frontend/lib/api.ts
Labels: deployment, config

#64 Add environment configuration for production deployment in CI/CD workflow
  .github/workflows/node.js.yml
Labels: deployment, config

#65 Refactor Dockerfile to properly define and use build arguments for environment variables
  frontend/Dockerfile
Labels: deployment, config

#66 Update Dockerfile to set runtime environment variables for public API and Matomo configurations
  frontend/Dockerfile
Labels: deployment, config

#67 Fh 72/docker frontend build args
  .github/workflows/node.js.yml
  frontend/Dockerfile
Labels: deployment, config

#68 Use npm ci for backend Dockerfile + add build argument variables for future CD
  backend/Dockerfile
  backend/start.sh
Labels: deployment, config

#69 Page Projet Détail
  .env
  backend/prisma/fake-data.ts
  backend/prisma/migrations/20250507093526_add_status_checkpoints/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/checkpoints/checkpoints.controller.ts
  backend/src/checkpoints/checkpoints.module.ts
  backend/src/checkpoints/checkpoints.service.ts
  backend/src/checkpoints/dto/checkpointStatus.dto.ts
  backend/src/checkpoints/dto/create-checkpoint.dto.ts
  backend/src/checkpoints/dto/update-checkpoint.dto.ts
  backend/src/common/chat/chat.service.ts
  backend/src/conversations/conversations.controller.ts
  backend/src/conversations/conversations.service.ts
  backend/src/documents/documents.controller.ts
  backend/src/documents/documents.service.ts
  backend/src/job-postings/dto/create-job-posting.dto.ts
  backend/src/job-postings/job-postings.controller.ts
  backend/src/job-postings/job-postings.service.ts
  backend/src/projects/dto/create-project.dto.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
  frontend/actions/checkPoints.ts
  frontend/actions/conversations.ts
  frontend/actions/jobPostings.ts
  frontend/actions/login.ts
  frontend/actions/projects.ts
  frontend/app/login/page.tsx
  frontend/app/project/[id]/page.tsx
  frontend/components/common/calendar/ProjectTimeline.tsx
  frontend/components/common/card/checkPointsStats.tsx
  frontend/components/common/conversation/conversation.tsx
  frontend/components/ui/calendar.tsx
  frontend/components/ui/menubar.tsx
  frontend/components/ui/navigation-menu.tsx
  frontend/hooks/useSocket.ts
  frontend/lib/interfaces.ts
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: bug, backend, frontend

#71 Fh 58/cd backend dockerfile
  .github/workflows/node.js.yml
  compose.prod.yaml
Labels: deployment, config

#72 Make documentId optional in CreateFreelanceDto
  backend/src/freelances/dto/create-freelance.dto.ts
Labels: backend

#73 Fh 75/prod backend cors
  .env
  .github/workflows/node.js.yml
  backend/Dockerfile
  backend/src/app.module.ts
  backend/src/auth/auth.controller.spec.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/common/authentik/authentik.module.ts
  backend/src/common/authentik/authentik.service.ts
  backend/src/common/environment/environment.service.ts
  backend/src/common/upload/upload.module.ts
  backend/src/common/upload/upload.service.ts
  backend/src/conversations/conversations.controller.spec.ts
  backend/src/conversations/conversations.module.ts
  backend/src/documents/documents.module.ts
  backend/src/messages/message.module.ts
  backend/src/messages/messages.controller.spec.ts
  compose.prod.yaml
Labels: backend, deployment

#75 Pin MinIO Docker image version to RELEASE.2025-04-22T22-12-26Z
  compose.yaml
Labels: config

#76 Stripe + devis Stripe + Création de compte client Stripe + page de paiement Stripe
  .env
  backend/package-lock.json
  backend/package.json
  backend/prisma/fake-data.ts
  backend/prisma/migrations/20250514213227_add_amount_checkoint_project/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/checkpoints/checkpoints.controller.ts
  backend/src/checkpoints/checkpoints.module.ts
  backend/src/checkpoints/checkpoints.service.ts
  backend/src/checkpoints/dto/create-checkpoint.dto.ts
  backend/src/checkpoints/dto/update-checkpoint.dto.ts
  backend/src/common/chat/chat.service.ts
  backend/src/common/stripe/dto/activate-customer-connection.dto.ts
  backend/src/common/stripe/dto/create-account-connection.dto.ts
  backend/src/common/stripe/dto/create-checkout-session.dto.ts
  backend/src/common/stripe/dto/create-invoice-stripe.dto.ts
  backend/src/common/stripe/dto/create-product-stripe.dto.ts
  backend/src/common/stripe/dto/create-quote-stripe.dto.ts
  backend/src/common/stripe/stripe.controller.ts
  backend/src/common/stripe/stripe.module.ts
  backend/src/common/stripe/stripe.service.ts
  backend/src/freelances/freelances.controller.spec.ts
  backend/src/main.ts
  backend/src/projects/projects.controller.spec.ts
  backend/src/quote/dto/create-quote.dto.ts
  backend/src/quote/quote.controller.ts
  backend/src/quote/quote.module.ts
  backend/src/quote/quote.service.ts
  compose.yaml
  frontend/actions/checkPoints.ts
  frontend/app/project/[id]/page.tsx
  frontend/components/common/calendar/ProjectTimeline.tsx
  frontend/components/ui/calendar.tsx
  frontend/lib/interfaces.ts
  frontend/package-lock.json
Labels: backend
